import Courses from "../assets/img/courses.svg";
import Practice from "../assets/img/document-text.svg";
import List from "../assets/img/task-square.svg";

export const items = [
  {
    title: "My Lessons",
    url: "/dashboard",
    icon: Courses,
  },
  {
    title: "Question Bank",
    url: "/questionbank",
    icon: List,
  },
  {
    title: "Practice Problems",
    url: "/practiceproblems",
    icon: Practice,
  },
];

export const questiondata = [
  {
    id: 1,
    title: "How many feet are in a mile? 1",
    course: "Algebra",
    topic: "Identify rational & irrational numbers",
    standard: "k2",
    difficultylevel: "Advanced",
    tags: ["JavaScript", "React"],
    status: "Draft",
  },
  {
    id: 2,
    title: "How many feet are in a mile? 2",
    course: "Geometry",
    topic: "Identify rational & irrational numbers",
    standard: "k2",
    difficultylevel: "Intermediate",
    tags: ["JavaScript", "Closures"],
    status: "Published",
  },
  {
    id: 3,
    title: "How many feet are in a mile? 3",
    course: "Algebra",
    topic: "Identify rational & irrational numbers",
    standard: "k2",
    difficultylevel: "Beginner",
    tags: ["JavaScript", "Closures"],
    status: "Published",
  },
  {
    id: 4,
    title: "How many feet are in a mile? 4",
    course: "Algebra",
    topic: "Linear Equations",
    standard: "k3",
    difficultylevel: "Beginner",
    tags: ["Math", "Equations"],
    status: "Draft",
  },
  {
    id: 5,
    title: "How many feet are in a mile? 5",
    course: "Calculus",
    topic: "Limits and Continuity",
    standard: "k4",
    difficultylevel: "Advanced",
    tags: ["Math", "Calculus"],
    status: "Published",
  },
  {
    id: 6,
    title: "How many feet are in a mile? 6",
    course: "Geometry",
    topic: "Triangles and Their Properties",
    standard: "k2",
    difficultylevel: "Intermediate",
    tags: ["Geometry", "Shapes"],
    status: "Draft",
  },
  {
    id: 7,
    title: "How many feet are in a mile? 7",
    course: "Geometry",
    topic: "Factors and Multiples",
    standard: "k2",
    difficultylevel: "Beginner",
    tags: ["Math", "Numbers"],
    status: "Published",
  },
  {
    id: 8,
    title: "How many feet are in a mile? 8",
    course: "Geometry",
    topic: "Prime and Composite Numbers",
    standard: "k3",
    difficultylevel: "Advanced",
    tags: ["Math", "Numbers"],
    status: "Published",
  },
  {
    id: 9,
    title: "How many feet are in a mile? 9",
    course: "Statistics",
    topic: "Mean, Median, and Mode",
    standard: "k4",
    difficultylevel: "Intermediate",
    tags: ["Statistics", "Data"],
    status: "Draft",
  },
  {
    id: 10,
    title: "How many feet are in a mile? 10",
    course: "Geometry",
    topic: "Solve Quadratic Equations",
    standard: "k3",
    difficultylevel: "Advanced",
    tags: ["Algebra", "Equations"],
    status: "Published",
  },
  {
    id: 11,
    title: "How many feet are in a mile? 11",
    course: "Geometry",
    topic: "Perimeter and Area",
    standard: "k2",
    difficultylevel: "Beginner",
    tags: ["Geometry", "Measurement"],
    status: "Draft",
  },
  {
    id: 12,
    title: "How many feet are in a mile? 12",
    course: "Geometry",
    topic: "Sets and Subsets",
    standard: "k2",
    difficultylevel: "Intermediate",
    tags: ["Math", "Logic"],
    status: "Published",
  },
  {
    id: 13,
    title: "How many feet are in a mile? 13",
    course: "Probability",
    topic: "Basics of Probability",
    standard: "k3",
    difficultylevel: "Beginner",
    tags: ["Statistics", "Probability"],
    status: "Published",
  },
  {
    id: 14,
    title: "How many feet are in a mile? 14",
    course: "Algebra",
    topic: "Polynomials",
    standard: "k4",
    difficultylevel: "Advanced",
    tags: ["Math", "Algebra"],
    status: "Draft",
  },
  {
    id: 15,
    title: "How many feet are in a mile? 15",
    course: "Geometry",
    topic: "Real Numbers",
    standard: "k2",
    difficultylevel: "Beginner",
    tags: ["Math", "Numbers"],
    status: "Published",
  },
  {
    id: 16,
    title: "How many feet are in a mile? 16",
    course: "Trigonometry",
    topic: "Trigonometric Ratios",
    standard: "k3",
    difficultylevel: "Intermediate",
    tags: ["Math", "Trigonometry"],
    status: "Published",
  },
  {
    id: 17,
    title: "How many feet are in a mile? 17",
    course: "Calculus",
    topic: "Differentiation Basics",
    standard: "k4",
    difficultylevel: "Advanced",
    tags: ["Math", "Calculus"],
    status: "Draft",
  },
  {
    id: 18,
    title: "How many feet are in a mile? 18",
    course: "Statistics",
    topic: "Data Interpretation",
    standard: "k2",
    difficultylevel: "Intermediate",
    tags: ["Statistics", "Analysis"],
    status: "Published",
  },
  {
    id: 19,
    title: "How many feet are in a mile? 19",
    course: "Geometry",
    topic: "Angles in Geometry",
    standard: "k2",
    difficultylevel: "Beginner",
    tags: ["Geometry", "Angles"],
    status: "Published",
  },
  {
    id: 20,
    title: "How many feet are in a mile? 20",
    course: "Geometry",
    topic: "Coordinate Geometry Basics",
    standard: "k3",
    difficultylevel: "Intermediate",
    tags: ["Math", "Geometry"],
    status: "Draft",
  },
  {
    id: 21,
    title: "How many feet are in a mile? 21",
    course: "Probability",
    topic: "Conditional Probability",
    standard: "k4",
    difficultylevel: "Advanced",
    tags: ["Statistics", "Probability"],
    status: "Published",
  },
  {
    id: 22,
    title: "How many feet are in a mile? 22",
    course: "Geometry",
    topic: "Algebraic Expressions",
    standard: "k2",
    difficultylevel: "Intermediate",
    tags: ["Math", "Algebra"],
    status: "Published",
  },
  {
    id: 23,
    title: "How many feet are in a mile? 23",
    course: "Algebra",
    topic: "Solving Inequalities",
    standard: "k3",
    difficultylevel: "Advanced",
    tags: ["Math", "Equations"],
    status: "Draft",
  },
  {
    id: 24,
    title: "How many feet are in a mile? 24",
    course: "Geometry",
    topic: "Properties of Circles",
    standard: "k2",
    difficultylevel: "Beginner",
    tags: ["Geometry", "Shapes"],
    status: "Published",
  },
  {
    id: 25,
    title: "How many feet are in a mile? 25",
    course: "Trigonometry",
    topic: "Introduction to Identities",
    standard: "k3",
    difficultylevel: "Intermediate",
    tags: ["Math", "Trigonometry"],
    status: "Draft",
  },
  {
    id: 26,
    title: "How many feet are in a mile? 26",
    course: "Geometry",
    topic: "Number Systems",
    standard: "k2",
    difficultylevel: "Beginner",
    tags: ["Math", "Numbers"],
    status: "Published",
  },
  {
    id: 27,
    title: "How many feet are in a mile? 27",
    course: "Calculus",
    topic: "Integration Basics",
    standard: "k4",
    difficultylevel: "Advanced",
    tags: ["Math", "Calculus"],
    status: "Draft",
  },
  {
    id: 28,
    title: "How many feet are in a mile? 28",
    course: "Geometry",
    topic: "3D Shapes and Volumes",
    standard: "k2",
    difficultylevel: "Intermediate",
    tags: ["Geometry", "Shapes"],
    status: "Published",
  },
  {
    id: 29,
    title: "How many feet are in a mile? 29",
    course: "Statistics",
    topic: "Variance and Standard Deviation",
    standard: "k4",
    difficultylevel: "Advanced",
    tags: ["Statistics", "Analysis"],
    status: "Draft",
  },
  {
    id: 30,
    title: "How many feet are in a mile? 30",
    course: "Geometry",
    topic: "Simplifying Fractions",
    standard: "k2",
    difficultylevel: "Beginner",
    tags: ["Math", "Fractions"],
    status: "Published",
  },
  // {
  //   id: 30,
  //   title: "How many feet are in a mile? 30",
  //   course: "Geometry",
  //   topic: "Simplifying Fractions",
  //   standard: "k2",
  //   difficultylevel: "Beginner",
  //   tags: ["Math", "Fractions"],
  //   status: "Published",
  // },
  // {
  //   id: 30,
  //   title: "How many feet are in a mile? 30",
  //   course: "Geometry",
  //   topic: "Simplifying Fractions",
  //   standard: "k2",
  //   difficultylevel: "Beginner",
  //   tags: ["Math", "Fractions"],
  //   status: "Published",
  // },
];
